[tox]
env_list = py310, py311, py312, py313, py314

[testenv]
deps =
    pytest
    pytest-asyncio

commands = pytest

[testenv:mypy]
description = run static type checks
deps =
extras = typecheck
commands = mypy
